### ISSUE TITLE
0.0.1: license?

### ISSUE THREAD

**Issue by kloczek** [Bartpab/meson-py#2]
Looks like https://github.com/Bartpab/meson-py/blob/master/LICENSE is empty and I cannot find any traces of licence uder which this module is provided.

**Comment by kloczek** [comment]
gentle ping ..

**Comment by kloczek** [comment]
BTW: is it possible to add 0.0.1 git tag?

**Comment by tillea** [comment]
Urgent ping - for both.  We need to package mesonpy for Debian to upgrade scipy but we can't package it without license text.
Extra points for setting a git tag.

**Comment by eli-schwartz** [comment]
This is NOT the project that SciPy depends on. At all.

SciPy depends on meson-python, which definitely has license info. I'm not entirely sure what a wrapper for Electron would have to do with SciPy, honestly. :P

**Comment by tillea** [comment]
Am Wed, Dec 14, 2022 at 08:38:23PM -0800 schrieb Eli Schwartz:
> This is NOT the project that SciPy depends on. At all.
> 
> SciPy depends on meson-python, which definitely has license info. I'm not entirely sure what a wrapper for Electron would have to do with SciPy, honestly. :P
Thanks for the hint - I've found this out later after adding to this issue.  I think the issue should be fixed anyway.

**Comment by eli-schwartz** [comment]
Sure, it's good to fix this general issue in any repository, no matter how niche.

The flip side is that the author hasn't been active on github for a year, and this repository hasn't been updated in 5 years. I wouldn't worry too much if nothing ever comes of it.

**Comment by kloczek** [comment]
OK looks like I've hir wrong module 😋 
Closing.
