### ISSUE TITLE
`pip install --no-clean` does not preserve `mesonpy` build directory

### ISSUE THREAD

**Issue by mathstuf** [Bartpab/meson-py#4]
The use of `tempfile.TemporaryDirectory` in `Project.with_temp_working_dir` means that no debugging of the build directory can be done even if `--no-clean` is passed. There should be a supported way to keep the build directory around in case of problems.

**Comment by rgommers** [comment]
Wrong repo? I think you want this open issue here: https://github.com/mesonbuild/meson-python/issues/246

**Comment by mathstuf** [comment]
Oh, right. I forgot that the module name misled me on PyPI as well for this. Sorry for the noise.
